name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme MacClipboard -project MacClipboard.xcodeproj -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]} 