name: tests

on: [push]

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project MacClipboard.xcodeproj -scheme MacClipboard | xcpretty
          
      - name: Build Test
        run: |
          xcodebuild test -project MacClipboard.xcodeproj -scheme MacClipboard -destination 'platform=macOS' | xcpretty -s
          